"""initial_schema

Revision ID: 0f028c8226e5
Revises: 
Create Date: 2026-02-19 12:46:29.499878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f028c8226e5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisdictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geoid', sa.String(length=15), nullable=False),
    sa.Column('jurisdiction_type', sa.String(length=25), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=False),
    sa.Column('county_fips', sa.String(length=3), nullable=True),
    sa.Column('place_fips', sa.String(length=5), nullable=True),
    sa.Column('cousub_fips', sa.String(length=5), nullable=True),
    sa.Column('jurisdiction_name', sa.String(length=200), nullable=False),
    sa.Column('jurisdiction_name_lsad', sa.String(length=200), nullable=True),
    sa.Column('state_abbr', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.Column('county_name', sa.String(length=100), nullable=True),
    sa.Column('has_licensing_authority', sa.Boolean(), nullable=False),
    sa.Column('licensing_authority_name', sa.String(length=200), nullable=True),
    sa.Column('is_dry', sa.Boolean(), nullable=False),
    sa.Column('dry_wet_status', sa.String(length=10), nullable=True),
    sa.Column('control_status', sa.String(length=20), nullable=False),
    sa.Column('delegation_pattern', sa.String(length=50), nullable=True),
    sa.Column('land_area_sqm', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_independent_city', sa.Boolean(), nullable=False),
    sa.Column('census_year', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geoid', 'jurisdiction_type', 'census_year', name='uq_jurisdiction_natural_key'),
    schema='jurisdiction'
    )
    op.create_index(op.f('ix_jurisdiction_jurisdictions_geoid'), 'jurisdictions', ['geoid'], unique=False, schema='jurisdiction')
    op.create_index(op.f('ix_jurisdiction_jurisdictions_jurisdiction_type'), 'jurisdictions', ['jurisdiction_type'], unique=False, schema='jurisdiction')
    op.create_index(op.f('ix_jurisdiction_jurisdictions_state_fips'), 'jurisdictions', ['state_fips'], unique=False, schema='jurisdiction')
    op.create_index(op.f('ix_jurisdiction_jurisdictions_tier'), 'jurisdictions', ['tier'], unique=False, schema='jurisdiction')
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('phase_reached', sa.String(length=50), nullable=True),
    sa.Column('census_year', sa.Integer(), nullable=False),
    sa.Column('states_processed', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('total_jurisdictions', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id'),
    schema='jurisdiction'
    )
    op.create_table('state_classifications',
    sa.Column('state_fips', sa.String(length=2), nullable=False),
    sa.Column('state_abbr', sa.String(length=2), nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.Column('is_territory', sa.Boolean(), nullable=False),
    sa.Column('control_status', sa.String(length=20), nullable=False),
    sa.Column('has_local_licensing', sa.Boolean(), nullable=False),
    sa.Column('delegates_to_county', sa.Boolean(), nullable=False),
    sa.Column('delegates_to_municipality', sa.Boolean(), nullable=False),
    sa.Column('delegates_to_mcd', sa.Boolean(), nullable=False),
    sa.Column('is_strong_mcd_state', sa.Boolean(), nullable=False),
    sa.Column('has_local_option_law', sa.Boolean(), nullable=False),
    sa.Column('local_option_level', sa.String(length=30), nullable=True),
    sa.Column('abc_agency_name', sa.String(length=200), nullable=True),
    sa.Column('abc_agency_url', sa.String(length=500), nullable=True),
    sa.Column('research_status', sa.String(length=20), nullable=False),
    sa.Column('research_source', sa.String(length=500), nullable=True),
    sa.Column('research_notes', sa.Text(), nullable=True),
    sa.Column('last_verified_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('state_fips'),
    sa.UniqueConstraint('state_abbr'),
    schema='jurisdiction'
    )
    op.create_table('census_geographies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geoid', sa.String(length=15), nullable=False),
    sa.Column('geo_layer', sa.String(length=20), nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=False),
    sa.Column('county_fips', sa.String(length=3), nullable=True),
    sa.Column('place_fips', sa.String(length=5), nullable=True),
    sa.Column('cousub_fips', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_lsad', sa.String(length=200), nullable=True),
    sa.Column('lsad_code', sa.String(length=5), nullable=True),
    sa.Column('functional_status', sa.String(length=1), nullable=True),
    sa.Column('class_fips', sa.String(length=5), nullable=True),
    sa.Column('land_area_sqm', sa.BigInteger(), nullable=True),
    sa.Column('water_area_sqm', sa.BigInteger(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('census_year', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_fips'], ['jurisdiction.state_classifications.state_fips'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geoid', 'geo_layer', 'census_year', name='uq_census_geo_natural_key'),
    schema='jurisdiction'
    )
    op.create_index(op.f('ix_jurisdiction_census_geographies_geo_layer'), 'census_geographies', ['geo_layer'], unique=False, schema='jurisdiction')
    op.create_index(op.f('ix_jurisdiction_census_geographies_geoid'), 'census_geographies', ['geoid'], unique=False, schema='jurisdiction')
    op.create_index(op.f('ix_jurisdiction_census_geographies_state_fips'), 'census_geographies', ['state_fips'], unique=False, schema='jurisdiction')
    op.create_table('research_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_fips', sa.String(length=2), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('finding', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=10), nullable=False),
    sa.Column('researcher', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['state_fips'], ['jurisdiction.state_classifications.state_fips'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='jurisdiction'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_notes', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_census_geographies_state_fips'), table_name='census_geographies', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_census_geographies_geoid'), table_name='census_geographies', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_census_geographies_geo_layer'), table_name='census_geographies', schema='jurisdiction')
    op.drop_table('census_geographies', schema='jurisdiction')
    op.drop_table('state_classifications', schema='jurisdiction')
    op.drop_table('pipeline_runs', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_jurisdictions_tier'), table_name='jurisdictions', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_jurisdictions_state_fips'), table_name='jurisdictions', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_jurisdictions_jurisdiction_type'), table_name='jurisdictions', schema='jurisdiction')
    op.drop_index(op.f('ix_jurisdiction_jurisdictions_geoid'), table_name='jurisdictions', schema='jurisdiction')
    op.drop_table('jurisdictions', schema='jurisdiction')
    # ### end Alembic commands ###
